// Generated by https://quicktype.io

export interface Region {
  name: Name;
  tld: string[];
  cca2: string;
  ccn3: string;
  cca3: string;
  cioc?: string;
  independent: boolean;
  status: Status;
  unMember: boolean;
  currencies: Currencies;
  idd: Idd;
  capital: string[];
  altSpellings: string[];
  region: RegionElement;
  subregion: Subregion;
  languages: { [key: string]: string };
  translations: { [key: string]: Translation };
  latlng: number[];
  landlocked: boolean;
  borders?: string[];
  area: number;
  demonyms: Demonyms;
  flag: string;
  maps: Maps;
  population: number;
  gini?: { [key: string]: number };
  fifa?: string;
  car: Car;
  timezones: string[];
  continents: RegionElement[];
  flags: Flags;
  coatOfArms: CoatOfArms;
  startOfWeek: StartOfWeek;
  capitalInfo: CapitalInfo;
  postalCode?: PostalCode;
}

export interface CapitalInfo {
  latlng: number[];
}

export interface Car {
  signs: string[];
  side: Side;
}

export enum Side {
  Left = 'left',
  Right = 'right',
}

export interface CoatOfArms {
  png?: string;
  svg?: string;
}

export enum RegionElement {
  Africa = 'Africa',
  Asia = 'Asia',
}

export interface Currencies {
  ZAR?: TartuGecko;
  SSP?: TartuGecko;
  DZD?: TartuGecko;
  EGP?: TartuGecko;
  XOF?: TartuGecko;
  RWF?: TartuGecko;
  MUR?: TartuGecko;
  GMD?: TartuGecko;
  XAF?: TartuGecko;
  ZMW?: TartuGecko;
  ERN?: TartuGecko;
  MAD?: TartuGecko;
  EUR?: TartuGecko;
  MZN?: TartuGecko;
  SLL?: TartuGecko;
  TND?: TartuGecko;
  SOS?: TartuGecko;
  SDG?: Sdg;
  STN?: TartuGecko;
  MGA?: TartuGecko;
  KMF?: TartuGecko;
  GBP?: TartuGecko;
  SHP?: TartuGecko;
  USD?: TartuGecko;
  NGN?: TartuGecko;
  LSL?: TartuGecko;
  LRD?: TartuGecko;
  CVE?: TartuGecko;
  BIF?: TartuGecko;
  UGX?: TartuGecko;
  SCR?: TartuGecko;
  MWK?: TartuGecko;
  ZWL?: TartuGecko;
  LYD?: TartuGecko;
  KES?: TartuGecko;
  BWP?: TartuGecko;
  MRU?: TartuGecko;
  SZL?: TartuGecko;
  NAD?: TartuGecko;
  TZS?: TartuGecko;
  AOA?: TartuGecko;
  CDF?: TartuGecko;
  DJF?: TartuGecko;
  GHS?: TartuGecko;
  GNF?: TartuGecko;
  ETB?: TartuGecko;
}

export interface TartuGecko {
  name: string;
  symbol: string;
}

export interface Sdg {
  name: string;
}

export interface Demonyms {
  eng: Eng;
  fra?: Eng;
}

export interface Eng {
  f: string;
  m: string;
}

export interface Flags {
  png: string;
  svg: string;
  alt?: string;
}

export interface Idd {
  root: string;
  suffixes: string[];
}

export interface Maps {
  googleMaps: string;
  openStreetMaps: string;
}

export interface Name {
  common: string;
  official: string;
  nativeName: { [key: string]: Translation };
}

export interface Translation {
  official: string;
  common: string;
}

export interface PostalCode {
  format: string;
  regex: string;
}

export enum StartOfWeek {
  Monday = 'monday',
  Sunday = 'sunday',
}

export enum Status {
  OfficiallyAssigned = 'officially-assigned',
}

export enum Subregion {
  EasternAfrica = 'Eastern Africa',
  MiddleAfrica = 'Middle Africa',
  NorthernAfrica = 'Northern Africa',
  SouthernAfrica = 'Southern Africa',
  WesternAfrica = 'Western Africa',
}
